### ISSUE TITLE
License!

### ISSUE THREAD

**Issue by teymour-aldridge** [lanesawyer/standardnotes-rs#1]
Hi!

I'd like to contribute, but would prefer for there to be some infrastructure in place about copyright before I do so. 

I personally think it'd be neat if this was open source (but it's of course entirely your choice 😃) under a Mozilla Public License v2 (which IMO neatly combines the best of the GNU Public Licenses with more permissive licenses such as the MIT and BSD licenses).

In any case, this looks like a cool project and best of luck.

**Comment by lanesawyer** [comment]
Thanks for the comment! I was literally thinking last night about how I don't have a README, CONTRIBUTING, or LICENSE document created yet. And this will absolutely be open source! :grin: 

I'll get those added, most likely today!

**Comment by teymour-aldridge** [comment]
Cool!

I'll try and submit a few PRs!

**Comment by teymour-aldridge** [comment]
Oh, also a code of conduct (e.g. the contributor covenant code of conduct) might also be useful.

**Comment by lanesawyer** [comment]
Added the GNU Affero General Public License v3.0, Contributor Covenant, basic README, and basic CONTRIBUTOR documentation!
